[build-system]
requires = [
    "setuptools>=50.3",
    "wheel>=0.35",
    "cffi>=1.14.2",
    "pycparser>=2.14",
    "pcpp>=1.21",
]

[tool.black]
line-length = 120
py36 = true
target-version = ["py36"]

[tool.isort]
profile = "black"
py_version = "36"
skip_gitignore = true
line_length = 120
